### ISSUE TITLE
Add support for full url in NetworkLocation

### ISSUE THREAD

**Issue by ITAYC0HEN** [CERT-Polska/mwdb_iocextract#11]
Currently, there is no way to present a full URL (e.g "http://domain.pl:1234/path") in NetworkLocation

https://github.com/CERT-Polska/mwdb_iocextract/blob/a8b2d510db2282981b55f78119b157f3ff4fbf48/src/model.py#L74-L85

This is a problem, because "NetworkLocation" doesn't keep note of the scheme (http://,   https://) that is used. Thus, one can't transform a NetworkLocation ovject back to a url. Even if they will do:
``` python
url = f"{nl.hostname}{nl.path}"
```
You still don't know the scheme, whether it is http or https for example.

Adding a `url` member to NetworkLocation will be very useful.

**Comment by nazywam** [comment]
I think this was actually addressed by https://github.com/CERT-Polska/mwdb_iocextract/commit/3bb3a97fa9704ef5f393e71c2f2fefee5cb36705?

Not sure why the commits date(Apr 1, 2020) is earlier than this issue (Sep 2, 2020). But it looks like this issue not longer exists in the current codebase :thinking: 

@ITAYC0HEN could you confirm this?
