### ISSUE TITLE
Incompatibility with mwdblib 4.0.0

### ISSUE THREAD

**Issue by a1ext** [CERT-Polska/mwdb_iocextract#15]
Hi, I recently updated to the latest `mwdblib==4.0.0` and I spot an issue with `mwdb_iocextract`. 
It is related to renamed `Malwarecage` to `MWDB` so some imports are failing in the lines like
```py
from mwdblib import Malwarecage 
```

|    package                         |   version      |
|-----------------------------|--------------|
| mwdb-iocextract version |  latest `1.1.1`  |
| mwdblib version              | `4.0.0`           |

**Comment by psrok1** [comment]
Uh, mwdblib is not even mentioned in requirements. WIll be fixed soon.
